PinnedTaskSectionを実装した
nitic-pbl-p8/lockerai pull request #2
Opened 2023-10-24 08:50 UTC by st20089ki

## Related Issues

- close: #1 

## Design
https://www.figma.com/file/xNKAhniAfPPTsL987xRCVe/website?type=design&node-id=232-464&mode=design&t=euVSzLap6WvLVWZu-4

2023-10-27 03:01 UTC, dino3616 requested changes
マークアップに関しては満点なのでサジェストはなしす^〜
ただパフォーマンスなり設計なりの観点からの MUST サジェスチョンがいくつかあるので対応していただけると 🙏
(OPTION が付いてるやつは文字通り修正しても修正しなくてもええでなやつなので、余裕があればでおkす)

2023-12-08 05:11 UTC, st20089ki commented on apps/website/src/module/dashboard/ui/page/pinned-task-section/pinned-task-section.presenter.tsx
> +    <section className="flex flex-col items-center gap-8">
直しました https://github.com/nitic-pbl-p8/lockerai/pull/2/commits/ce142c3d01a54fe95b58f9ce3ecf7971fb05b82d

2023-12-08 05:11 UTC, st20089ki commented on apps/website/src/module/dashboard/ui/page/pinned-task-section/pinned-task-section.presenter.tsx
> +          </div>
直しました https://github.com/nitic-pbl-p8/lockerai/pull/2/commits/ce142c3d01a54fe95b58f9ce3ecf7971fb05b82d

2023-12-08 05:13 UTC, Sigumaa approved these changes
LGTM^_^

2023-12-08 05:46 UTC, merged